# Generated by Django 4.2.30 on 2026-06-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Espera', 'En Espera'), ('Atencion', 'En Atención'), ('Derivado', 'Derivado')], default='Espera', max_length=20)),
                ('tiempo_llegada', models.DateTimeField(auto_now_add=True)),
                ('tiempo_atencion', models.DateTimeField(blank=True, null=True)),
                ('tiempo_salida', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
