# Generated by Django 4.2.23 on 2026-06-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='modulo_atencion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Módulo de Atención'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('Espera', 'En Espera'), ('Atencion', 'En Atención'), ('Derivado', 'Derivado'), ('Finalizado', 'Finalizado')], default='Espera', max_length=20),
        ),
    ]
