# Generated by Django 4.2.23 on 2026-06-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_turno_modulo_atencion_alter_turno_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='fue_derivado',
            field=models.BooleanField(default=False, verbose_name='¿Fue Derivado?'),
        ),
    ]
